# Generated by Django 4.2.1 on 2023-05-12 10:20

import Movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filmid', models.CharField(default='********', max_length=8)),
                ('chapterid', models.IntegerField(default=0)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filmid', models.CharField(default=Movies.models.rand_id, max_length=8)),
                ('title', models.TextField()),
            ],
        ),
    ]
